/* Danh mục vật liệu bàn giao chi tiết — 3 loại sản phẩm (theo tài liệu CĐT) */

export interface HandoverGroup { group: string; rows: [string, string][] }
export interface HandoverTable { tab: string; caption: string; groups: HandoverGroup[] }

export const HANDOVER_TABLES: HandoverTable[] = [
  {
    tab: "Căn hộ hoàn thiện cơ bản",
    caption: "Danh mục vật liệu bàn giao dự kiến – Căn hộ hoàn thiện cơ bản",
    groups: [
      { group: "Sàn", rows: [
        ["Phòng khách, khu vực bếp", "Porcelain vân gỗ 150x900mm hoặc tương đương · Viglacera/ Á Mỹ hoặc tương đương"],
        ["Phòng ngủ", "Porcelain vân gỗ 150x900mm hoặc tương đương · Viglacera/ Á Mỹ hoặc tương đương"],
        ["Phòng tắm", "Porcelain 300x600mm chống trượt hoặc tương đương · Viglacera/ Á Mỹ hoặc tương đương"],
        ["Ngạch cửa", "Đá Marble hoặc tương đương"],
        ["Ban công, Lô gia", "Porcelain vân gỗ 150x900mm/ Porcelain 300x600mm chống trượt hoặc tương đương · Viglacera/ Á Mỹ hoặc tương đương"],
      ]},
      { group: "Tường", rows: [
        ["Tường xây bao căn hộ", "Gạch nung/ gạch không nung theo thiết kế Việt Nam"],
        ["Tường xây ngăn trong căn hộ", "Gạch nung/ gạch không nung theo thiết kế Việt Nam"],
        ["Hoàn thiện tường phòng khách, bếp, phòng ngủ", "Sơn nội thất, màu sắc theo thiết kế Jotun hoặc tương đương"],
        ["Hoàn thiện tường phòng tắm, vệ sinh", "Porcelain 300x600mm hoặc tương đương · Viglacera/ Á Mỹ hoặc tương đương"],
        ["Hoàn thiện tường ban công, lô gia", "Sơn ngoại thất, màu sắc theo thiết kế Jotun hoặc tương đương"],
        ["Len phòng khách, bếp", "Len gạch/ PVC/ HDF màu sắc theo thiết kế"],
        ["Len phòng ngủ", "Len gạch/ PVC/ HDF màu sắc theo thiết kế"],
        ["Len ban công, lô gia", "Len gạch màu sắc theo thiết kế hoặc tương đương"],
      ]},
      { group: "Trần", rows: [
        ["Phòng khách, bếp, phòng ngủ", "Trần thạch cao, sơn nội thất màu sắc theo thiết kế - Vĩnh Tường hoặc tương đương · - Jotun hoặc tương đương"],
        ["WC", "Trần thạch cao chống ẩm, sơn nội thất màu sắc theo thiết kế - Vĩnh Tường hoặc tương đương · - Jotun hoặc tương đương"],
        ["Ban công, lô gia", "Sơn ngoại thất, màu sắc theo thiết kế Jotun hoặc tương đương"],
      ]},
      { group: "Cửa đi, cửa sổ", rows: [
        ["Cửa chính căn hộ", "Cửa gỗ chống cháy EI60, hoàn thiện Laminate màu sắc theo thiết kế An Cường/ American Door hoặc tương đương"],
        ["Khóa điện tử Cửa chính căn hộ", "Khóa từ 05 phương thức mở khóa: Vân tay, mã số, thẻ từ, chìa khóa cơ, điều khiển qua app Nhà cung cấp khóa Häfele hoặc tương đương"],
        ["Cửa phòng ngủ trong căn hộ", "Cửa gỗ, hoàn thiện Melamine màu sắc theo thiết kế An Cường/ American Door hoặc tương đương"],
        ["Cửa phòng vệ sinh trong căn hộ", "Cửa WPC, màu sắc hoàn thiện Galaxy/ Sunwood hoặc tương đương"],
        ["Phụ kiện cửa", "Häfele hoặc tương đương"],
        ["Cửa Ban công, Logia, cửa sổ mặt ngoài", "Cửa nhôm kính Kính VIFG/VFG hoặc tương đương · Phụ kiện Draho/ Kinlong hoặc tương đương · G. công, l. đặt: BM Windows hoặc tương đương"],
      ]},
      { group: "Phòng tắm", rows: [
        ["Chậu rửa (Lavabo) + vòi rửa", "Kohler hoặc tương đương"],
        ["Tủ lavabo", "Tủ gỗ công nghiệp, mặt đá nhân tạo/ đá marble màu sắc theo thiết kế hoặc tương đương · Mỹ Khang/ An Cường/ Casta hoặc tương đương"],
        ["Tủ gương", "Tủ gỗ công nghiệp, gương kính thuỷ màu sắc theo thiết kế hoặc tương đương · Mỹ Khang/ An Cường/ Casta hoặc tương đương"],
        ["Sen tắm", "Sen tắm đứng Kohler hoặc tương đương"],
        ["Bồn cầu", "Kohler hoặc tương đương"],
        ["Vòi xịt", "Kohler hoặc tương đương"],
        ["Thanh treo khăn, móc áo, móc treo giấy vệ sinh", "INNOCI hoặc tương đương"],
        ["Khu tắm đứng", "Vách kính + cửa kính cường lực, khung inox Kính VIFG/VFG hoặc tương đương · Phụ kiện Kinlong hoặc tương đương"],
        ["Máy nước nóng - lạnh", "Ferroli hoặc tương đương"],
      ]},
      { group: "Bếp", rows: [
        ["Tủ bếp trên", "Tủ gỗ chống ẩm hoàn thiện Laminate/ Acrylic màu sắc theo thiết kế hoặc tương đương · Mỹ Khang/ An Cường/ Casta hoặc tương đương"],
        ["Tủ bếp dưới", "Tủ gỗ chống ẩm hoàn thiện Laminate/ Acrylic; mặt bếp, tường bếp: đá nhân tạo/ đá marble; màu sắc theo thiết kế hoặc tương đương · Mỹ Khang/ An Cường/ Casta hoặc tương đương"],
        ["Bồn rửa + vòi rửa căn 1B", "Bồn rửa inox 304/ đá nhân tạo; vòi rửa inox 304 Häfele/ Teka/ Innoci/ Kluger hoặc tương đương"],
        ["Bếp từ + máy hút mùi căn 1B", "Bếp từ 2 vùng nấu/ 3 vùng nấu hoặc tương đương · Panasonic/ Häfele/ Teka hoặc tương đương"],
        ["Bồn rửa + vòi rửa căn 2B, 3B", "Bồn rửa inox 304/ đá nhân tạo; vòi rửa inox 304 Häfele/ Teka/ Innoci/ Kluger hoặc tương đương"],
        ["Bếp từ + máy hút mùi căn 2B, 3B", "Bếp từ 3 vùng nấu hoặc tương đương · Panasonic/ Häfele/ Teka hoặc tương đương"],
      ]},
      { group: "Thiết bị điện nước", rows: [
        ["Tủ điện căn hộ", "Theo thiết kế Tủ điện Hager/ LS; thiết bị đóng cắt LS hoặc tương đương"],
        ["Cáp điện", "Theo thiết kế Cadivi/ LS hoặc tương đương"],
        ["Đèn phòng khách, bếp, phòng ngủ, WC", "Đèn downlight âm trần theo thiết kế Simex hoặc tương đương"],
        ["Đèn ban công, lô gia", "Đèn downlight ốp trần theo thiết kế Simex hoặc tương đương"],
        ["Công tắc điện, ổ cắm điện", "Công tắc, ổ cắm điện theo thiết kế (bao gồm công tắc chuông cửa) Hager hoặc tương đương"],
        ["Truyền hình cáp, Internet", "Đầu chờ cáp dịch vụ truyền hình tại phòng khách, Internet không dây Nhà mạng cung cấp theo nhu cầu khách hàng"],
        ["Video Door Phone", "Màn hình cảm ứng 7’, chức năng gọi sảnh, gọi giữa các căn hộ Aiphone (Nhật Bản) hoặc tương đương"],
        ["Quạt hút gió phòng WC", "Panasonic hoặc tương đương"],
        ["Hệ thống ống cấp thoát nước Hệ thống Máy lạnh Hệ thống PCCC", "Ống nhựa Đồng Nai hoặc tương đương · Không đầu tư thiết bị, chỉ lắp đặt đầu chờ, ống gas và ống nước ngưng đủ điều kiện lắp máy lạnh sau này Theo thiết kế tòa nhà đáp ứng QCVN, TCVN và quy định PCCC hiện hành"],
      ]},
    ],
  },
  {
    tab: "Căn hộ thô · tầng 28 & 40",
    caption: "Danh mục vật liệu bàn giao dự kiến – Căn hộ bàn giao thô – tầng 28 T1, T2 · tầng 40 T3A, T3B",
    groups: [
      { group: "Sàn", rows: [
        ["Phòng khách, khu vực bếp", "Bàn giao thô"],
        ["Phòng ngủ", "Bàn giao thô"],
        ["Phòng tắm", "Cán nền, chống thấm cuốn chân tường 300mm"],
        ["Ngạch cửa", "Ngạch cửa chính: Đá Marble hoặc tương đương"],
        ["Ban công, Lô gia", "Porcelain vân gỗ 150x900mm/ Porcelain 300x600mm chống trượt hoặc tương đương · Viglacera/ Á Mỹ hoặc tương đương"],
      ]},
      { group: "Tường", rows: [
        ["Tường xây bao căn hộ", "Gạch nung/ gạch không nung theo thiết kế Việt Nam"],
        ["Tường xây ngăn trong căn hộ", "Không bàn giao"],
        ["Hoàn thiện tường phòng khách, bếp, phòng ngủ", "Không bàn giao"],
        ["Hoàn thiện tường phòng tắm, vệ sinh", "Không bàn giao"],
        ["Hoàn thiện tường ban công, lô gia", "Sơn ngoại thất, màu sắc theo thiết kế Jotun hoặc tương đương"],
        ["Len phòng khách, bếp", "Không bàn giao"],
        ["Len phòng ngủ", "Không bàn giao"],
        ["Len ban công, lô gia", "Len gạch màu sắc theo thiết kế hoặc tương đương"],
      ]},
      { group: "Trần", rows: [
        ["Phòng khách, bếp, phòng ngủ", "Bàn giao thô"],
        ["WC", "Bàn giao thô"],
        ["Ban công, lô gia", "Sơn ngoại thất, màu sắc theo thiết kế Jotun hoặc tương đương"],
      ]},
      { group: "Cửa đi, cửa sổ", rows: [
        ["Cửa chính căn hộ", "Cửa gỗ chống cháy EI60, hoàn thiện Laminate màu sắc theo thiết kế An Cường/ American Door hoặc tương đương"],
        ["Khóa điện tử Cửa chính căn hộ", "Khóa từ 05 phương thức mở khóa: Vân tay, mã số, thẻ từ, chìa khóa cơ, điều khiển qua app Nhà cung cấp khóa Häfele hoặc tương đương"],
        ["Cửa phòng ngủ trong căn hộ", "Không bàn giao"],
        ["Cửa phòng vệ sinh trong căn hộ", "Không bàn giao"],
        ["Phụ kiện cửa", "Häfele hoặc tương đương"],
        ["Cửa Ban công, Logia, cửa sổ mặt ngoài", "Cửa nhôm kính Kính VIFG/VFG hoặc tương đương · Phụ kiện Draho/ Kinlong hoặc tương đương · G. công, l. đặt: BM Windows hoặc tương đương"],
      ]},
      { group: "Phòng tắm", rows: [
        ["Chậu rửa (Lavabo) + vòi rửa", "Không bàn giao"],
        ["Tủ lavabo", "Không bàn giao"],
        ["Tủ gương", "Không bàn giao"],
        ["Sen tắm", "Không bàn giao"],
        ["Bồn cầu", "Không bàn giao"],
        ["Vòi xịt", "Không bàn giao"],
        ["Thanh treo khăn, móc áo, móc treo giấy vệ sinh", "Không bàn giao"],
        ["Khu tắm đứng", "Không bàn giao"],
        ["Máy nước nóng - lạnh", "Không bàn giao"],
      ]},
      { group: "Bếp", rows: [
        ["Tủ bếp trên", "Không bàn giao"],
        ["Tủ bếp dưới", "Không bàn giao"],
        ["Bồn rửa + vòi rửa căn 1B", "Không bàn giao"],
        ["Bếp từ + máy hút mùi căn 1B", "Không bàn giao"],
        ["Bồn rửa + vòi rửa căn 2B, 3B", "Không bàn giao"],
        ["Bếp từ + máy hút mùi căn 2B, 3B", "Không bàn giao"],
      ]},
      { group: "Thiết bị điện nước", rows: [
        ["Tủ điện căn hộ", "Vỏ tủ + CB tổng Tủ điện Hager/ LS; thiết bị đóng cắt LS hoặc tương đương"],
        ["Cáp điện", "Cấp nguồn đến tủ điện tổng và cáp cho đèn ban công, lô gia Cadivi/ LS hoặc tương đương"],
        ["Đèn phòng khách, bếp, phòng ngủ, WC", "Không bàn giao"],
        ["Đèn ban công, lô gia", "Đèn downlight ốp trần theo thiết kế Simex hoặc tương đương"],
        ["Công tắc điện, ổ cắm điện", "Công tắc đèn ban công Đầu chờ lắp đặt chuông cửa Hager hoặc tương đương"],
        ["Truyền hình cáp, Internet", "Đầu chờ cáp quang tại cửa vào căn hộ"],
        ["Video Door Phone", "Box chờ cho nút nhấn chuông cửa, cáp chờ cho màn hình chuông cửa đến vị trí màn hình theo thiết kế (Không bàn giao thiết bị)"],
        ["Quạt hút gió phòng WC", "Không bàn giao"],
        ["Hệ thống ống cấp thoát nước Hệ thống Máy lạnh Hệ thống PCCC", "Đầu chờ có van khóa cấp nước Đầu chờ + bịt đầu ống thoát nước theo thiết kế của Dự án Không bàn giao Theo thiết kế tòa nhà đáp ứng QCVN, TCVN và quy định PCCC hiện hành"],
      ]},
    ],
  },
  {
    tab: "Shophouse",
    caption: "Danh mục vật liệu bàn giao dự kiến – Shophouse khối đế",
    groups: [
      { group: "Sàn", rows: [
        ["Phòng khách, khu vực bếp", "Bàn giao thô Cầu thang bê tông"],
        ["Phòng ngủ", "N/A"],
        ["Phòng tắm", "Cán nền, chống thấm cuốn chân tường 300mm"],
        ["Ngạch cửa", "Ngạch cửa chính cho cửa gỗ: Đá Marble hoặc tương đương"],
        ["Ban công, Lô gia", "Porcelain vân gỗ 150x900mm/ Porcelain 300x600mm chống trượt hoặc tương đương · Viglacera/ Á Mỹ hoặc tương đương"],
      ]},
      { group: "Tường", rows: [
        ["Tường xây bao căn hộ", "Gạch nung/ gạch không nung theo thiết kế Việt Nam"],
        ["Tường xây ngăn trong căn hộ", "Không bàn giao"],
        ["Hoàn thiện tường phòng khách, bếp, phòng ngủ", "Không bàn giao"],
        ["Hoàn thiện tường phòng tắm, vệ sinh", "Không bàn giao"],
        ["Hoàn thiện tường ban công, lô gia", "Sơn ngoại thất, màu sắc theo thiết kế Jotun hoặc tương đương"],
        ["Len phòng khách, bếp", "Không bàn giao"],
        ["Len phòng ngủ", "N/A"],
        ["Len ban công, lô gia", "Len gạch màu sắc theo thiết kế hoặc tương đương"],
      ]},
      { group: "Trần", rows: [
        ["Phòng khách, bếp, phòng ngủ", "Bàn giao thô/ đóng trần che ống kỹ thuật tầng 2 các căn shophouse 2 tầng"],
        ["WC", "Bàn giao thô"],
        ["Ban công, lô gia", "Sơn ngoại thất, màu sắc theo thiết kế Jotun hoặc tương đương"],
      ]},
      { group: "Cửa đi, cửa sổ", rows: [
        ["Cửa chính căn hộ", "Cửa nhôm kính bản lề sàn/ Cửa gỗ chống cháy EI60, hoàn thiện Laminate màu sắc theo thiết kế BM Windows hoặc tương đương · An Cường/ American Door hoặc tương đương"],
        ["Khóa điện tử Cửa chính căn hộ", "Cửa nhôm kính bản lề sàn: Khóa bản lề sàn Häfele hoặc tương đương · Cửa gỗ: Khóa từ 05 phương thức mở khóa: Vân tay, mã số, thẻ từ, chìa khóa cơ, điều khiển qua app Nhà cung cấp khóa Häfele hoặc tương đương"],
        ["Cửa phòng ngủ trong căn hộ", "N/A"],
        ["Cửa phòng vệ sinh trong căn hộ", "Không bàn giao"],
        ["Phụ kiện cửa", "Häfele hoặc tương đương"],
        ["Cửa Ban công, Logia, cửa sổ mặt ngoài", "Cửa nhôm kính Kính VIFG/VFG hoặc tương đương · Phụ kiện Draho/ Kinlong hoặc tương đương · G. công, l. đặt: BM Windows hoặc tương đương"],
      ]},
      { group: "Phòng tắm", rows: [
        ["Chậu rửa (Lavabo) + vòi rửa", "Không bàn giao"],
        ["Tủ lavabo", "Không bàn giao"],
        ["Tủ gương", "Không bàn giao"],
        ["Sen tắm", "Không bàn giao"],
        ["Bồn cầu", "Không bàn giao"],
        ["Vòi xịt", "Không bàn giao"],
        ["Thanh treo khăn, móc áo, móc treo giấy vệ sinh", "Không bàn giao"],
        ["Khu tắm đứng", "Không bàn giao"],
        ["Máy nước nóng - lạnh", "Không bàn giao"],
      ]},
      { group: "Bếp", rows: [
        ["Tủ bếp trên", "Không bàn giao"],
        ["Tủ bếp dưới", "Không bàn giao"],
        ["Bồn rửa + vòi rửa căn 1B", "Không bàn giao"],
        ["Bếp từ + máy hút mùi căn 1B", "Không bàn giao"],
        ["Bồn rửa + vòi rửa căn 2B, 3B", "Không bàn giao"],
        ["Bếp từ + máy hút mùi căn 2B, 3B", "Không bàn giao"],
      ]},
      { group: "Thiết bị điện nước", rows: [
        ["Tủ điện căn hộ", "Vỏ tủ + CB tổng Tủ điện Hager/ LS; thiết bị đóng cắt LS hoặc tương đương"],
        ["Cáp điện", "Cấp nguồn đến tủ điện tổng và cáp cho đèn ban công, lô gia Cadivi/ LS hoặc tương đương"],
        ["Đèn phòng khách, bếp, phòng ngủ, WC", "Không bàn giao"],
        ["Đèn ban công, lô gia", "Đèn downlight ốp trần theo thiết kế Simex hoặc tương đương"],
        ["Công tắc điện, ổ cắm điện", "Công tắc đèn ban công Hager hoặc tương đương"],
        ["Truyền hình cáp, Internet", "Đầu chờ cáp quang tại cửa vào căn hộ"],
        ["Video Door Phone", "Không bàn giao"],
        ["Quạt hút gió phòng WC", "Không bàn giao"],
        ["Hệ thống ống cấp thoát nước Hệ thống Máy lạnh Hệ thống PCCC", "Đầu chờ cấp nước Đầu chờ thoát nước theo thiết kế của Dự án Không bàn giao Theo thiết kế tòa nhà đáp ứng QCVN, TCVN và quy định PCCC hiện hành"],
      ]},
    ],
  },
];
