export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    CHANGE_PASSWORD: '/auth/change-password',
    ME: '/auth/me',
  },
  NEWS: {
    CATEGORIES: '/articles/categories',
    LIST: '/articles',
    PUBLISHED: '/articles/published',
    DETAIL: (id: string) => `/articles/${id}`,
    DETAIL_BY_SLUG: (slug: string) => `/articles/by-slug/${slug}`,
    CREATE: '/articles',
    UPDATE: (id: string) => `/articles/${id}`,
    DELETE: (id: string) => `/articles/${id}`,
    FAQS: (id: string) => `/articles/${id}/faqs`,
    LOGS: (id: string) => `/articles/${id}/logs`,
  },
  MEDIA: {
    UPLOAD: '/media/upload',
    DELETE: (id: string) => `/media/${id}`,
    LIST: '/media',
  },
  ACCOUNTS: {
    LIST: '/accounts',
    DETAIL: (id: string) => `/accounts/${id}`,
    CREATE: '/accounts',
    UPDATE: (id: string) => `/accounts/${id}`,
    DELETE: (id: string) => `/accounts/${id}`,
    PERMISSIONS: '/accounts/permissions',
    NEWS_REVIEWERS: '/accounts/news-reviewers',
    PROJECT_REVIEWERS: '/accounts/project-reviewers',
    ASSIGN_PERMISSIONS: (id: string) => `/accounts/${id}/permissions`,
  },
  RECRUITMENT: {
    LIST: '/recruitment/jobs',
    PUBLISHED: '/recruitment/jobs/published',
    DETAIL: (id: string) => `/recruitment/jobs/${id}`,
    DETAIL_BY_SLUG: (slug: string) => `/recruitment/jobs/by-slug/${slug}`,
    CREATE: '/recruitment/jobs',
    UPDATE: (id: string) => `/recruitment/jobs/${id}`,
    DELETE: (id: string) => `/recruitment/jobs/${id}`,
    STATUS: (id: string) => `/recruitment/jobs/${id}/status`,
    LOGS: (id: string) => `/recruitment/jobs/${id}/logs`,
    APPLICATIONS: '/recruitment/applications',
    APPLICATION_DETAIL: (id: string) => `/recruitment/applications/${id}`,
    APPLICATION_STATUS: (id: string) => `/recruitment/applications/${id}/status`,
    APPLICATION_LOGS: (id: string) => `/recruitment/applications/${id}/logs`,
  },
  MAGAZINES: {
    LIST: '/magazines',
    ADMIN_LIST: '/magazines/all',
    DETAIL: (id: string) => `/magazines/${id}`,
    CREATE: '/magazines',
    UPDATE: (id: string) => `/magazines/${id}`,
    DELETE: (id: string) => `/magazines/${id}`,
    PUBLISH: (id: string) => `/magazines/${id}/publish`,
    UNPUBLISH: (id: string) => `/magazines/${id}/unpublish`,
  },
  PROJECTS: {
    LIST: '/projects',
    PUBLISHED: '/projects/published',
    DETAIL: (id: string) => `/projects/${id}`,
    DETAIL_BY_SLUG: (slug: string) => `/projects/by-slug/${slug}`,
    CREATE: '/projects',
    UPDATE: (id: string) => `/projects/${id}`,
    FAQS: (id: string) => `/projects/${id}/faqs`,
    DELETE: (id: string) => `/projects/${id}`,
    STATUS: (id: string) => `/projects/${id}/status`,
    SUBMIT: (id: string) => `/projects/${id}/submit`,
    PUBLISH: (id: string) => `/projects/${id}/publish`,
    REJECT: (id: string) => `/projects/${id}/reject`,
    REVOKE: (id: string) => `/projects/${id}/revoke`,
    LOGS: (id: string) => `/projects/${id}/logs`,
  },
  AGENTS: {
    LIST: '/agents',
    DETAIL: (id: string) => `/agents/${id}`,
    CREATE: '/agents',
    UPDATE: (id: string) => `/agents/${id}`,
    DELETE: (id: string) => `/agents/${id}`,
  },
  HONORS: {
    PUBLIC_CATEGORIES: '/honors/public/categories',
    CATEGORIES: '/honors/categories',
    CATEGORY: (slug: string) => `/honors/categories/${slug}`,
    CATEGORY_AGENTS: (slug: string) => `/honors/categories/${slug}/agents`,
  },
  MONTHLY_HONORS: {
    PUBLIC_LIST: '/monthly-honors/public',
    LIST: '/monthly-honors',
    DETAIL: (id: string) => `/monthly-honors/${id}`,
    CREATE: '/monthly-honors',
    UPDATE: (id: string) => `/monthly-honors/${id}`,
    DELETE: (id: string) => `/monthly-honors/${id}`,
  },
  ANNUAL_HONORS: {
    PUBLIC_LIST: '/annual-honors/public',
    LIST: '/annual-honors',
    DETAIL: (id: string) => `/annual-honors/${id}`,
    CREATE: '/annual-honors',
    UPDATE: (id: string) => `/annual-honors/${id}`,
    DELETE: (id: string) => `/annual-honors/${id}`,
    CATEGORY_AGENTS: (id: string, slug: string) =>
      `/annual-honors/${id}/categories/${slug}/agents`,
  },
  ACADEMY_COURSES: {
    PUBLIC_LIST: '/academy-courses/public',
    PUBLIC_TAGS: '/academy-courses/public/tags',
    LIST: '/academy-courses',
    DETAIL: (id: string) => `/academy-courses/${id}`,
    CREATE: '/academy-courses',
    UPDATE: (id: string) => `/academy-courses/${id}`,
    DELETE: (id: string) => `/academy-courses/${id}`,
    TAGS: '/academy-courses/tags',
    TAG_DETAIL: (id: string) => `/academy-courses/tags/${id}`,
  },
  CONSULTATION: {
    SUBMIT: '/consultation',
  },
} as const;
