export { AcademyHeroSection } from "./AcademyHeroSection";
export { AcademyCoursesSection } from "./AcademyCoursesSection";
export { AcademyRoadmapSection } from "./AcademyRoadmapSection";
export { AcademyOnlineSection } from "./AcademyOnlineSection";
export { AcademyActivitiesSection } from "./AcademyActivitiesSection";
export { AcademyMyEraSection } from "./AcademyMyEraSection";
export { AcademyTestimonialsSection } from "./AcademyTestimonialsSection";
export { AcademyFaqSection } from "./AcademyFaqSection";
export { AcademyPage } from "./AcademyPage";
